
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ADD DIV DUMP MUL PRINT READ SET SUB id numComando : '(' READ id ')'Comando : '(' PRINT Exp ')'Comando : '(' SET id Exp ')'Comando : DUMPExp : '(' ADD Exp Termo ')'Exp : '(' SUB Exp Termo ')'Exp : TermoExp : '(' MUL Termo Factor ')'Termo : '(' DIV Termo Factor ')'Termo : FactorFactor : '(' Exp ')'Factor : numFactor : id"
    
_lr_action_items = {'(':([0,5,8,10,11,12,13,14,16,18,19,20,23,24,25,26,27,28,32,35,36,37,38,],[2,8,8,-7,-10,-12,-13,8,8,8,26,26,26,-11,26,8,32,32,8,-5,-6,-8,-9,]),'DUMP':([0,],[3,]),'$end':([1,3,15,21,29,],[0,-4,-1,-2,-3,]),'READ':([2,],[4,]),'PRINT':([2,],[5,]),'SET':([2,],[6,]),'id':([4,5,6,8,10,11,12,13,14,16,18,19,20,23,24,25,26,27,28,32,35,36,37,38,],[7,13,14,13,-7,-10,-12,-13,13,13,13,13,13,13,-11,13,13,13,13,13,-5,-6,-8,-9,]),'num':([5,8,10,11,12,13,14,16,18,19,20,23,24,25,26,27,28,32,35,36,37,38,],[12,12,-7,-10,-12,-13,12,12,12,12,12,12,-11,12,12,12,12,12,-5,-6,-8,-9,]),')':([7,9,10,11,12,13,17,22,24,30,31,33,34,35,36,37,38,],[15,21,-7,-10,-12,-13,24,29,-11,35,36,37,38,-5,-6,-8,-9,]),'ADD':([8,],[16,]),'SUB':([8,],[18,]),'MUL':([8,],[19,]),'DIV':([8,26,],[20,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comando':([0,],[1,]),'Exp':([5,8,14,16,18,26,32,],[9,17,22,23,25,17,17,]),'Termo':([5,8,14,16,18,19,20,23,25,26,32,],[10,10,10,10,10,27,28,30,31,10,10,]),'Factor':([5,8,14,16,18,19,20,23,25,26,27,28,32,],[11,11,11,11,11,11,11,11,11,11,33,34,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comando","S'",1,None,None,None),
  ('Comando -> ( READ id )','Comando',4,'p_Comando_ler','sexp_yacc.py',8),
  ('Comando -> ( PRINT Exp )','Comando',4,'p_Comando_escrever','sexp_yacc.py',13),
  ('Comando -> ( SET id Exp )','Comando',5,'p_Comando_atrib','sexp_yacc.py',17),
  ('Comando -> DUMP','Comando',1,'p_Comando_despejar','sexp_yacc.py',21),
  ('Exp -> ( ADD Exp Termo )','Exp',5,'p_Exp_add','sexp_yacc.py',25),
  ('Exp -> ( SUB Exp Termo )','Exp',5,'p_Exp_sub','sexp_yacc.py',29),
  ('Exp -> Termo','Exp',1,'p_Exp_termo','sexp_yacc.py',33),
  ('Exp -> ( MUL Termo Factor )','Exp',5,'p_Termo_mul','sexp_yacc.py',37),
  ('Termo -> ( DIV Termo Factor )','Termo',5,'p_Termo_div','sexp_yacc.py',41),
  ('Termo -> Factor','Termo',1,'p_Termo_factor','sexp_yacc.py',49),
  ('Factor -> ( Exp )','Factor',3,'p_Factor_group','sexp_yacc.py',53),
  ('Factor -> num','Factor',1,'p_Factor_num','sexp_yacc.py',57),
  ('Factor -> id','Factor',1,'p_Factor_id','sexp_yacc.py',61),
]
